### PR TITLE
fix(module): export default plugin

### LINKED ISSUE #1: TS1192: Module '"[...]/node_modules/cem-plugin-better-lit-types/dist/index"' has no default export.
When using the plugin by:
```typescript
import extractLitTypes from 'cem-plugin-better-lit-types'
```

Typescript reports a problem that the package itself has no default export:
```
TS1192: Module '"[...]/node_modules/cem-plugin-better-lit-types/dist/index"' has no default export.
```

This is technically true, as the index does not have a default export, but the plugin is supposed to supersede that. While on runtime, this does happen; it is not detected in the linting stage.

### PR DESCRIPTION
**Pull request by Bitaru**
### Description
Seems like the reexport of the default export can't be correctly handled.
In this PR we export `{ plugin }` from `./plugin` and ` plugin as default` from the index

closes: #1

### CODE REVIEW

File: src/plugin.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ const createGenerator = (manifest: any) => {
 /**
  * Creates better types for LitElement
  */
-export default {
+export const plugin = {
```
Comment (adaliszk) [inline src/plugin.ts]: Perhaps, instead of `plugin`, it could be `betterLitTypes` so that it would enable:
```typescript
import { betterLitTypes } from 'cem-plugin-better-lit-types'
```

Comment (Bitaru) [reply src/plugin.ts]: Yeah, makes more sense
